#!/usr/bin/env node
/**
 * Generates the reading themes block in app/css/00-tokens-base.css.
 *
 *   node scripts/gen-themes.mjs          → rewrite block between THEMES:BEGIN/END markers
 *   node scripts/gen-themes.mjs --check  → print WCAG contrast report only
 *
 * Palettes are the OFFICIAL values of well-known schemes (Solarized, Gruvbox, Nord,
 * Catppuccin, Rosé Pine, GitHub Primer, One Dark, Tokyo Night, Dracula, Kindle sepia, iA Writer).
 * Where an official text/accent colour misses the readability target against our panes,
 * it is nudged along OKLCH lightness only (hue/chroma kept) — see the report.
 *
 * Targets: body text (bc) >= 7:1 (WCAG AAA), links/accent (p) >= 4.5:1 (AA),
 * measured against BOTH --b1 (page) and --b2 (panes/sidebar).
 */
import fs from 'node:fs';
import path from 'node:path';
import { fileURLToPath } from 'node:url';

const root = path.resolve(path.dirname(fileURLToPath(import.meta.url)), '..');
const cssPath = path.join(root, 'app', 'css', '00-tokens-base.css');
const BEGIN = '/* THEMES:BEGIN (generated by scripts/gen-themes.mjs — do not edit by hand) */';
const END = '/* THEMES:END */';

/* ── colour math ─────────────────────────────────────────── */
const hex2rgb = (h) => [1, 3, 5].map((i) => parseInt(h.slice(i, i + 2), 16) / 255);
const rgb2hex = (c) => '#' + c.map((v) => Math.round(Math.min(1, Math.max(0, v)) * 255).toString(16).padStart(2, '0')).join('');
const lin = (v) => (v <= 0.04045 ? v / 12.92 : ((v + 0.055) / 1.055) ** 2.4);
const delin = (v) => (v <= 0.0031308 ? v * 12.92 : 1.055 * v ** (1 / 2.4) - 0.055);

function lum(h) {
	const [r, g, b] = hex2rgb(h).map(lin);
	return 0.2126 * r + 0.7152 * g + 0.0722 * b;
}
function contrast(a, b) {
	const [x, y] = [lum(a), lum(b)].sort((p, q) => q - p);
	return (x + 0.05) / (y + 0.05);
}
function hex2oklch(h) {
	const [r, g, b] = hex2rgb(h).map(lin);
	const l = Math.cbrt(0.4122214708 * r + 0.5363325363 * g + 0.0514459929 * b);
	const m = Math.cbrt(0.2119034982 * r + 0.6806995451 * g + 0.1073969566 * b);
	const s = Math.cbrt(0.0883024619 * r + 0.2817188376 * g + 0.6299787005 * b);
	const L = 0.2104542553 * l + 0.793617785 * m - 0.0040720468 * s;
	const A = 1.9779984951 * l - 2.428592205 * m + 0.4505937099 * s;
	const B = 0.0259040371 * l + 0.7827717662 * m - 0.808675766 * s;
	return { L, C: Math.hypot(A, B), H: ((Math.atan2(B, A) * 180) / Math.PI + 360) % 360 };
}
function oklch2hex({ L, C, H }) {
	const A = C * Math.cos((H * Math.PI) / 180);
	const B = C * Math.sin((H * Math.PI) / 180);
	const l = (L + 0.3963377774 * A + 0.2158037573 * B) ** 3;
	const m = (L - 0.1055613458 * A - 0.0638541728 * B) ** 3;
	const s = (L - 0.0894841775 * A - 1.291485548 * B) ** 3;
	return rgb2hex([
		4.0767416621 * l - 3.3077115913 * m + 0.2309699292 * s,
		-1.2684380046 * l + 2.6097574011 * m - 0.3413193965 * s,
		-0.0041960863 * l - 0.7034186147 * m + 1.707614701 * s,
	].map(delin));
}
const mix = (a, b, t) => rgb2hex(hex2rgb(a).map((v, i) => v * (1 - t) + hex2rgb(b)[i] * t));
const fmt = (h) => {
	const { L, C, H } = hex2oklch(h);
	return `${(L * 100).toFixed(1)}% ${C.toFixed(3)} ${(C < 0.004 ? 0 : H).toFixed(0)}`;
};

/** Move colour along OKLCH lightness (away from bg) until `min` contrast on ALL bgs. */
function ensure(fg, bgs, min) {
	const ok = (c) => bgs.every((b) => contrast(c, b) >= min);
	if (ok(fg)) return { hex: fg, moved: false };
	const o = hex2oklch(fg);
	const darkBg = bgs.every((b) => lum(b) < 0.3);
	for (let i = 1; i <= 100; i++) {
		const L = darkBg ? Math.min(1, o.L + i * 0.005) : Math.max(0, o.L - i * 0.005);
		const c = oklch2hex({ ...o, L });
		if (ok(c)) return { hex: c, moved: true };
	}
	return { hex: darkBg ? '#ffffff' : '#000000', moved: true };
}
const onColor = (bg, cands) => cands.map((c) => [c, contrast(c, bg)]).sort((a, b) => b[1] - a[1])[0][0];

/* ── palettes (official values) ──────────────────────────── */
/* b1 page · b2 panes · b3 borders · bc text · p accent/link · code = code-block bg */
const THEMES = [
	/* light */
	{ id: 'sepia', name: 'Sepia Paper (Kindle)', group: 'light', b1: '#FBF0D9', b2: '#F4E7C8', b3: '#E2D1A8', bc: '#5F4B32', p: '#9A4A0A', s: '#4F7A55', a: '#A63D2F', su: '#4F7A55', wa: '#9A6700', er: '#A63D2F', code: '#2F2619' },
	{ id: 'solarized-light', name: 'Solarized Light', group: 'light', b1: '#fdf6e3', b2: '#eee8d5', b3: '#d6cfb8', bc: '#586e75', p: '#268bd2', s: '#2aa198', a: '#d33682', su: '#859900', wa: '#b58900', er: '#dc322f', code: '#002b36' },
	{ id: 'gruvbox-light', name: 'Gruvbox Light', group: 'light', b1: '#fbf1c7', b2: '#f2e5bc', b3: '#d5c4a1', bc: '#3c3836', p: '#076678', s: '#8f3f71', a: '#9d0006', su: '#79740e', wa: '#b57614', er: '#9d0006', code: '#282828' },
	{ id: 'rose-pine-dawn', name: 'Rosé Pine Dawn', group: 'light', b1: '#faf4ed', b2: '#fffaf3', b3: '#dfdad9', bc: '#575279', p: '#907aa9', s: '#56949f', a: '#b4637a', su: '#286983', wa: '#ea9d34', er: '#b4637a', code: '#1f1d2e' },
	{ id: 'catppuccin-latte', name: 'Catppuccin Latte', group: 'light', b1: '#eff1f5', b2: '#e6e9ef', b3: '#ccd0da', bc: '#4c4f69', p: '#1e66f5', s: '#8839ef', a: '#d20f39', su: '#40a02b', wa: '#df8e1d', er: '#d20f39', code: '#1e1e2e' },
	{ id: 'github-light', name: 'GitHub Light', group: 'light', b1: '#ffffff', b2: '#f6f8fa', b3: '#d1d9e0', bc: '#1f2328', p: '#0969da', s: '#8250df', a: '#cf222e', su: '#1a7f37', wa: '#9a6700', er: '#d1242f', code: '#161b22' },
	{ id: 'writer-light', name: 'Writer (iA, minimal)', group: 'light', b1: '#f7f7f7', b2: '#ffffff', b3: '#dcdcdc', bc: '#1a1a1a', p: '#1d6fa5', s: '#58bae7', a: '#b3261e', su: '#2e7d32', wa: '#9a6700', er: '#b3261e', code: '#1b1b1b' },
	{ id: 'contrast-light', name: 'High Contrast Light', group: 'light', b1: '#ffffff', b2: '#ffffff', b3: '#59636e', bc: '#0e1116', p: '#0349b4', s: '#622cbc', a: '#a0111f', su: '#055d20', wa: '#744500', er: '#a0111f', code: '#0e1116' },
	/* dark */
	{ id: 'github-dark', name: 'GitHub Dark', group: 'dark', b1: '#0d1117', b2: '#151b23', b3: '#3d444d', bc: '#e6edf3', p: '#4493f8', s: '#ab7df8', a: '#f85149', su: '#3fb950', wa: '#d29922', er: '#f85149', code: '#010409' },
	{ id: 'github-dimmed', name: 'GitHub Dark Dimmed', group: 'dark', b1: '#22272e', b2: '#2d333b', b3: '#444c56', bc: '#adbac7', p: '#539bf5', s: '#b083f0', a: '#e5534b', su: '#57ab5a', wa: '#c69026', er: '#e5534b', code: '#1c2128' },
	{ id: 'one-dark', name: 'One Dark', group: 'dark', b1: '#282c34', b2: '#2c313a', b3: '#3e4451', bc: '#abb2bf', p: '#61afef', s: '#c678dd', a: '#e06c75', su: '#98c379', wa: '#e5c07b', er: '#e06c75', code: '#21252b' },
	{ id: 'tokyo-night', name: 'Tokyo Night', group: 'dark', b1: '#1a1b26', b2: '#1f2335', b3: '#3b4261', bc: '#c0caf5', p: '#7aa2f7', s: '#bb9af7', a: '#f7768e', su: '#9ece6a', wa: '#e0af68', er: '#f7768e', code: '#16161e' },
	{ id: 'nord-polar', name: 'Nord', group: 'dark', b1: '#2e3440', b2: '#3b4252', b3: '#4c566a', bc: '#e5e9f0', p: '#88c0d0', s: '#81a1c1', a: '#bf616a', su: '#a3be8c', wa: '#ebcb8b', er: '#bf616a', code: '#262b35' },
	{ id: 'dracula-night', name: 'Dracula', group: 'dark', b1: '#282a36', b2: '#343746', b3: '#44475a', bc: '#f8f8f2', p: '#bd93f9', s: '#ff79c6', a: '#ff5555', su: '#50fa7b', wa: '#f1fa8c', er: '#ff5555', code: '#21222c' },
	{ id: 'solarized-dark', name: 'Solarized Dark', group: 'dark', b1: '#002b36', b2: '#073642', b3: '#1f4d59', bc: '#93a1a1', p: '#268bd2', s: '#2aa198', a: '#d33682', su: '#859900', wa: '#b58900', er: '#dc322f', code: '#00212b' },
	{ id: 'gruvbox-dark', name: 'Gruvbox Dark', group: 'dark', b1: '#282828', b2: '#32302f', b3: '#504945', bc: '#ebdbb2', p: '#83a598', s: '#d3869b', a: '#fb4934', su: '#b8bb26', wa: '#fabd2f', er: '#fb4934', code: '#1d2021' },
	{ id: 'rose-pine-moon', name: 'Rosé Pine Moon', group: 'dark', b1: '#232136', b2: '#2a273f', b3: '#393552', bc: '#e0def4', p: '#c4a7e7', s: '#9ccfd8', a: '#eb6f92', su: '#9ccfd8', wa: '#f6c177', er: '#eb6f92', code: '#191724' },
	{ id: 'catppuccin-mocha', name: 'Catppuccin Mocha', group: 'dark', b1: '#1e1e2e', b2: '#181825', b3: '#313244', bc: '#cdd6f4', p: '#89b4fa', s: '#cba6f7', a: '#f38ba8', su: '#a6e3a1', wa: '#f9e2af', er: '#f38ba8', code: '#11111b' },
	{ id: 'graphite', name: 'Graphite (Kindle dark)', group: 'dark', b1: '#2a2a2a', b2: '#303030', b3: '#474747', bc: '#d8d8d8', p: '#8ab4f8', s: '#c58af9', a: '#f28b82', su: '#81c995', wa: '#fdd663', er: '#f28b82', code: '#1f1f1f' },
	{ id: 'oled-black', name: 'OLED Black', group: 'dark', b1: '#000000', b2: '#0b0b0d', b3: '#26262b', bc: '#c8c8c8', p: '#7cb7ff', s: '#b794f6', a: '#ff7b72', su: '#56d364', wa: '#e3b341', er: '#ff7b72', code: '#0b0b0d' },
	{ id: 'contrast-dark', name: 'High Contrast Dark', group: 'dark', b1: '#010409', b2: '#0a0c10', b3: '#7a828e', bc: '#ffffff', p: '#71b7ff', s: '#cb9eff', a: '#ff9492', su: '#4ae168', wa: '#f0b72f', er: '#ff9492', code: '#010409' },
];

const SHAPE_LIGHT = ['--rounded-box: 0.85rem', '--rounded-btn: 0.55rem'];

function build(t) {
	const bgs = [t.b1, t.b2];
	const dark = t.group === 'dark';
	const notes = [];
	const text = ensure(t.bc, bgs, 7);
	if (text.moved) notes.push(`bc ${t.bc}→${text.hex}`);
	const bc = text.hex;
	const accent = ensure(t.p, bgs, 4.5);
	if (accent.moved) notes.push(`p ${t.p}→${accent.hex}`);
	const p = accent.hex;

	const pair = (c) => [c, onColor(c, [t.b1, bc, '#ffffff', '#000000'])];
	const [s, sc] = pair(t.s);
	const [a, ac] = pair(t.a);
	const [su, suc] = pair(t.su);
	const [wa, wac] = pair(t.wa);
	const [er, erc] = pair(t.er);
	const pc = onColor(p, [t.b1, bc, '#ffffff', '#000000']);
	const inline = ensure(bc, [mix(t.b2, t.b3, 0.55)], 7).hex;

	const vars = {
		p: fmt(p), pf: fmt(mix(p, dark ? '#ffffff' : '#000000', 0.12)), pc: fmt(pc),
		s: fmt(s), sf: fmt(mix(s, dark ? '#ffffff' : '#000000', 0.12)), sc: fmt(sc),
		a: fmt(a), af: fmt(mix(a, dark ? '#ffffff' : '#000000', 0.12)), ac: fmt(ac),
		n: fmt(bc), nf: fmt(mix(bc, t.b1, 0.15)), nc: fmt(t.b1),
		b1: fmt(t.b1), b2: fmt(t.b2), b3: fmt(t.b3), bc: fmt(bc),
		in: fmt(s), inc: fmt(sc),
		su: fmt(su), suc: fmt(suc), wa: fmt(wa), wac: fmt(wac), er: fmt(er), erc: fmt(erc),
	};
	const css = [
		`html[data-theme="${t.id}"] {`,
		`  color-scheme: ${dark ? 'dark' : 'light'};`,
		'  ' + Object.entries(vars).map(([k, v]) => `--${k}: ${v};`).join('\n  '),
		`  --rtlmd-inline-code-bg: ${mix(t.b2, t.b3, 0.55)};`,
		`  --rtlmd-inline-code-fg: ${inline};`,
		`  --rtlmd-inline-code-border: ${t.b3};`,
		`  --rtlmd-block-code-bg: ${t.code};`,
		`  --rtlmd-block-code-border: ${mix(t.code, '#ffffff', 0.16)};`,
		`  --rtlmd-table-border: ${mix(t.b3, bc, 0.12)};`,
		`  --rtlmd-table-head-bg: ${mix(t.b2, t.b3, 0.5)};`,
		`  --rtlmd-table-row-alt: ${mix(t.b2, t.b3, 0.22)};`,
		'}',
	].join('\n');

	const rep = {
		id: t.id,
		text: Math.min(contrast(bc, t.b1), contrast(bc, t.b2)),
		link: Math.min(contrast(p, t.b1), contrast(p, t.b2)),
		btn: contrast(pc, p),
		notes: notes.join(', '),
	};
	return { css, rep };
}

const built = THEMES.map(build);

console.log('theme                 text(≥7)  link(≥4.5)  btn   adjusted');
for (const { rep } of built) {
	console.log(
		`${rep.id.padEnd(21)} ${rep.text.toFixed(1).padStart(7)}  ${rep.link.toFixed(1).padStart(9)}  ${rep.btn.toFixed(1).padStart(5)}  ${rep.notes}`
	);
}

if (!process.argv.includes('--check')) {
	const ids = THEMES.map((t) => `html[data-theme="${t.id}"]`).join(',\n');
	const block = [
		BEGIN,
		`${ids} {\n  ${SHAPE_LIGHT.join(';\n  ')};\n  --rounded-badge: 1.5rem;\n  --animation-btn: 0.2s;\n  --animation-input: 0.2s;\n  --btn-focus-scale: 0.97;\n  --border-btn: 1px;\n  --tab-border: 1px;\n  --tab-radius: 0.5rem;\n}`,
		...built.map((b) => b.css),
		END,
	].join('\n\n');

	let css = fs.readFileSync(cssPath, 'utf8');
	const re = new RegExp(BEGIN.replace(/[.*+?^${}()|[\]\\]/g, '\\$&') + '[\\s\\S]*?' + END.replace(/[.*+?^${}()|[\]\\]/g, '\\$&'));
	if (re.test(css)) css = css.replace(re, () => block);
	else css = css.replace(/(\r?\n)html\.font-large \{/, (m, nl) => `${nl}${block}${nl}${nl}html.font-large {`);
	fs.writeFileSync(cssPath, css);
	console.log(`\nwrote ${THEMES.length} themes -> app/css/00-tokens-base.css`);
}
